/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package bigdata.project

import org.apache.spark.sql.SparkSession

object App {
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder.appName("MovieLens job").getOrCreate()
    val sqlContext = spark.sqlContext // needed to save as CSV
    import sqlContext.implicits._

    println("Spark works")
  }

  def greeting(): String = "Hello, world!"
}
